services:
  db:
    ports:
      - 5432:5432
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./docker-dev-volumes/pg_data:/var/lib/postgresql/data  # Persist PostgreSQL data
  old_fe : 
    build : 
      context : .
      dockerfile : Dockerfile-old_fe
    tty: true
    ports :     
      - 81:80
    volumes:
       - ./old_fe:/var/www
  old_be :  
    tty: true
    build : 
      context : .
      dockerfile : Dockerfile-old_be
    ports :     
        - 82:80
    volumes:
      - ./old_be:/var/www